### ISSUE TITLE
localize function significantly degrades performance

### ISSUE THREAD

**Issue by Everduin94** [nvim-treesitter/nvim-treesitter-angular#1]
### Issue
When using nvim-treesitter-angular and highlight enabled for typescript. If a localize function is added to the file, the performance degrades to a point that it is unusable.

### Example
https://user-images.githubusercontent.com/14320878/137019217-26a49f25-9ca4-4e97-a9ac-eef3a1892c96.mov

### My config
```lua
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
Plug 'nvim-treesitter/nvim-treesitter-angular'
    
lua << EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = "all", -- one of "all", "maintained" (parsers with maintainers), or a list of languages
  ignore_install = { "haskell" }, -- List of parsers to ignore installing
  highlight = {
    enable = true,              -- false will disable the whole extension
  },
}
EOF
```

NVIM v0.6.0-dev+446-g0fc8597f0

**Comment by steelsojka** [comment]
I don't think this specific to angular, but treesitter integration in
general. The current queries for typescript use language injection for
template tags, so that may be impacting it.

**Comment by Everduin94** [comment]
Yeah I'm not sure what specifically causes the performance degrading (I'm relatively new to nvim and treesitter 😬), but I posted the issue here because if I remove nvim-treesitter-angular plugin but keep nvim-treesitter + highlighting for typescript; I don't have the same performance issues.

### Example
https://user-images.githubusercontent.com/14320878/137026664-75fb97c1-9556-4a88-a38b-c0f9d78b406d.mov
