### ISSUE TITLE
Update ABI version

### ISSUE THREAD

**Issue by thraizz** [nvim-treesitter/nvim-treesitter-angular#2]
Hi, this parser is still sitting at ABI version 11, while my treesitter currently requires version 13. Would it be possible to upgrade this parser? :smiley_cat: 
Thanks and kind regards,
Aron

**Comment by ShooTeX** [comment]
any updates on this? Having the same issue

**Comment by ShooTeX** [comment]
anyone having the same issue, you could use my fork, I just regenerated the parser with an up-to-date treesitter cli:

https://github.com/ShooTeX/nvim-treesitter-angular

**Comment by michaelwestphal** [comment]
Has there been any movement on this issue?

**Comment by clason** [comment]
This repo only contains the queries, not the parser.
